config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  root to: 'welcome#index'
  
  get 'about' => 'welcome#about'
  
  resources :topics do
    resources :bookmarks, except: [:index] do
      resources :likes, only: [:create, :destroy]
    end
  end
  
  post :incoming, to: "incoming#create"
  
  devise_for :users
  resources :users, only: [:show]

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :topics, dependent: :destroy
  has_many :bookmarks
  has_many :likes, dependent: :destroy
  has_many :liked_bookmarks, through: :likes, source: :bookmark
  
#   after_initialize :set_defaults

  def set_defaults
    self.name = "Testing"
  end
  
  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to request.referrer, alert: "Sorry mate, but you don't have permission to perform that action." # exception.message
  end
 
  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
  end
  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
  def new
    @topic = Topic.find(the_topic)
    @bookmark = @topic.bookmarks.new
  end
  
  def create
    @topic = Topic.find(the_topic)
    @bookmark = @topic.bookmarks.build(bookmark_params)
    authorize @bookmark
    @bookmark.user = current_user
    @bookmark.save
    redirect_to @topic
  end
  
  def edit
    @topic = Topic.find(the_topic)
    @bookmark = Bookmark.find(the_bookmark)
    authorize @bookmark
    
  end
  
  def update
    @topic = Topic.find(the_topic)
    @bookmark = Bookmark.find(the_bookmark)
    authorize @bookmark
    @bookmark.update_attributes(bookmark_params)
    redirect_to @topic
  end
  
  def destroy
    @bookmark = Bookmark.find_by_id(the_bookmark)
    authorize @bookmark
    @bookmark.destroy
    redirect_to request.referrer # redirect back to same page
  end
  
  private
  
  def the_topic
    params[:topic_id]
  end
  
  def the_bookmark
    params[:id]
  end
  
  def bookmark_params
    params[:bookmark].permit(:url, :title)
  end
  
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  
  skip_before_action :verify_authenticity_token, only: [:create]
  
  def create
    
    @user = User.find_by_email(the_sender)
    if @user.nil?
      @user = User.new(
        name: the_name,
        email: the_sender,
        password: "password", # assign initial password for now...
        password_confirmation: "password"
      )
      @user.skip_confirmation! # skip for now to pass user story
      @user.save
      # Email instructions to new user to change the default password would be sent here?
    end
    
    # Re-write the below to account for universal topics and also individuals' topics?
    
    @topic = @user.topics.find_by_title(the_subject)
    if @topic.nil?
      @topic = @user.topics.build(title: the_subject)
      @topic.save
    end
    
    @bookmark = @topic.bookmarks.find_by_url(the_url)
    if @bookmark.nil?
      @bookmark = @topic.bookmarks.new(url: the_url, title: the_url, user_id: @user.id)
      @bookmark.user = @user
      @bookmark.save
    end
    
    head 200
  end
  
  private
  
  def the_sender
    params[:sender]
  end
  
  def the_name
    params[:from]
  end
  
  def the_subject
    params[:subject]
  end
  
  def the_url
    params["body-plain"].chomp
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @bookmark = Bookmark.find(the_bookmark)
    like = current_user.likes.build(bookmark: @bookmark)
    
    authorize like
    if like.save
      redirect_to request.referrer
    else
      flash[:error] = "Sorry mate, but something went wrong."
      redirect_to request.referrer
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(the_bookmark)
    like = current_user.liked(@bookmark)
    
    authorize like
    if like.destroy
      redirect_to request.referrer
    else
      flash[:error] = "Sorry mate, but something went wrong."
      redirect_to request.referrer
    end
  end
  
  private
  
  def the_bookmark
    params[:bookmark_id]
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @topic = Topic.new
  end

  def show
    @topic = the_topic
    @bookmarks = @topic.bookmarks.all
  end
  
  def create
    @topic = current_user.topics.build(params[:topic].permit(:title))
    @topic.save
    redirect_to request.referrer
  end
  
  def destroy
    @topic = the_topic
    authorize @topic
    @topic.destroy
    redirect_to request.referrer
  end
  
  private
  
  def the_topic
    Topic.find(params[:id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_bookmarks = current_user.bookmarks.all
    @liked_bookmarks = current_user.liked_bookmarks.all
    # @liked_bookmarks = Bookmark.where(id: current_user.likes.pluck(:bookmark_id))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/edit.html.erb
<div class="row">
  <div class="col-md-8">

    <h1 class="nudge-up-10">Edit Bookmark</h1>
    
    <%= form_for [@topic, @bookmark] do |f| %>

      <div class="form-group">
        <%= f.label :title %><br/>
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>      
      </div>

      <div class="form-group">
        <%= f.label :url %><br/>
        <%= f.text_field :url, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-default' %>
      </div>
    
    <% end %>
    
    <%= link_to "Back", :back, class: 'margin-left-5' %>
    
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="row">
  <div class="col-md-8">

    <h1 class="nudge-up-10">New Bookmark</h1>
    
    <%= form_for [@topic, @bookmark] do |f| %>

      <div class="form-group">
        <%= f.label :title %><br/>
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>      
      </div>

      <div class="form-group">
        <%= f.label :url %><br/>
        <%= f.text_field :url, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-default' %>
      </div>
    
    <% end %>
    
    <%= link_to "Back", :back, class: 'margin-left-5' %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="nav nav-tabs">
          <li><%= link_to "Blocmarks", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          
          <% if current_user %>
            <li><%= link_to "My Profile", users_show_path(current_user) %></li>
            <li><%= link_to "All Bookmarks", topics_path %></li>
          <% end %>
          
          <div class="pull-right user-info margin-top-10 margin-right-5">
            <% if current_user %>
              <%= link_to "#{current_user.name}", edit_user_registration_path %> | <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign in", new_user_session_path %> | <%= link_to "Sign up", new_user_registration_path %>
            <% end %>
          </div>
        </ul>
        
        
        
      </div>
    </div>
  
    
    <br/>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
      
  </div>
  

</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <% if like = current_user.liked(bookmark) %>
    <%= link_to "", [topic, bookmark, like], class: 'glyphicon glyphicon-thumbs-down remove-color', method: :delete %>
  <% else %>
    <%= link_to "", [topic, bookmark, Like.new], class: 'glyphicon glyphicon-thumbs-up remove-color', method: :post %>
  <% end %>
<% end %>

app/views/topics/index.html.erb
<% if policy(@topic).index? %>
<div class="row">
  <div class="col-md-8">

    <h1 class="nudge-up-10">Bookmarks: All by Topic</h1>

    <%= form_for @topic do |f| %>
      <%= f.text_field :title, class: 'form-control input-topic inline-block' %>
      <%= f.submit "Add Topic", class: 'btn btn-default inline-block' %>
    <% end %>
    
    <% @topics.each do |topic| %>
      <div class="list-group">  
        <h4 class="list-group-item list-group-item-info">
          <%= link_to topic.title, topic %> 
          <small><i class="remove-color">added by <%= topic.user.name %></i></small>
          <%= link_to "", topic, method: :delete, class: 'glyphicon glyphicon-remove-circle remove-color pull-right', data: { confirm: "Are you sure you want to remove #{topic.title}?" } %>
        </h4>            
        <div class="list-group-item">
          <% topic.bookmarks.each_with_index do |bookmark, index| %>
            <% unless index >= topic.bookmarks.count %>
              <p>
                <%= link_to bookmark.title, bookmark.url, target: "_blank", class: 'margin-left-10 margin-right-10' %>
                <%= render partial: 'likes/like', locals: { bookmark: bookmark, topic: topic } %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

  </div>
</div>
<% end %>

app/views/topics/show.html.erb
<div class="row">
  <div class="col-md-8">
    
    <h1 class="nudge-up-10">Bookmarks for <%= @topic.title %> <i class="remove-color">added by <%= @topic.user.name %></i></h1>
    
    <%= link_to "Add Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-default' %>

    <div class="list-group">
      <h4 class="list-group-item list-group-item-info remove-color"><%= @topic.title %></h4>
      <div class="list-group-item">
        <% @bookmarks.each do |bookmark| %>
          <p>
            <%= link_to bookmark.title, bookmark.url, target: "_blank", class: 'margin-left-10 margin-right-10' %>
            <%= render partial: 'likes/like', locals: { bookmark: bookmark, topic: @topic } %>
            <% if bookmark.user == current_user %>
              <%= link_to "", edit_topic_bookmark_path(@topic, bookmark), class: 'glyphicon glyphicon-edit remove-color' %>
              <%= link_to "", [@topic, bookmark], method: :delete, class: 'glyphicon glyphicon-remove-circle remove-color', data: { confirm: "Are you sure you want to remove #{bookmark.url}?" } %>
            <% end %>
          </p>
        <% end %>
        
      </div>
    </div>
    
    <%= link_to "Back", topics_path, class: 'margin-left-5' %>
    
  </div>
</div>

app/views/users/show.html.erb
<h1><%= current_user.name %></h1>

<div class="row">
  <div class="col-md-8">

    <div class="list-group">
      <h4 class="list-group-item list-group-item-info remove-color">My Bookmarks</h4>
      <div class="list-group-item">
        
        <table class="table">
          <thead>
            <tr>
              <td class="width-25">
                <strong class="remove-color">TOPIC</strong>
              </td>
              <td>
                <strong class="remove-color"> URL</strong>
              </td>
            </tr>
          </thead>
          <tbody>
            
            <% @user_bookmarks.each do |b| %>
              <tr>
                <td>
                  <%= b.topic.title %>
                </td>
                <td>
                  <%= link_to b.title, b.url, target: "_blank" %>
                </td>
              </tr>  
            <% end %>
            
          </tbody>
        </table>
          
      </div>
    </div>
    
    <div class="list-group">
      <h4 class="list-group-item list-group-item-info remove-color">Bookmarks I Like</h4>
      <div class="list-group-item">
        
        <table class="table">
          <thead>
            <tr>
              <td class="width-25">
                <strong class="remove-color">TOPIC</strong>
              </td>
              <td>
                <strong class="remove-color"> URL</strong>
              </td>
            </tr>
          </thead>
          <tbody>
            
            <% @liked_bookmarks.each do |b| %>
              <tr>
                <td>
                  <%= b.topic.title %>
                </td>
                <td>
                  <%= link_to b.title, b.url, target: "_blank" %>
                  <%= render partial: 'likes/like', locals: { bookmark: b, topic: b.topic } %>
                </td>
              </tr>  
            <% end %>
            
          </tbody>
        </table>
          
      </div>
    </div>    
    
    
    
  </div>
</div>

app/views/welcome/about.html.erb
<h1 class="nudge-up-10">About Blocmarks</h1>
<p>No fluff. No flashy distractions. Just pure bookmarking.</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1><span class="glyphicon glyphicon-star-empty nudge-down-5"></span>Blocmarks</h1>
  <p>Raw Social Bookmarking</p>
</div>